name: Visual Treats by KO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.58431
title: Visual Treats created and curated by Konrad Pitala
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
