name: Visual Treats by KO
favicon: null
layout_spectrum: 0.89527
typography_spectrum: 0.58431
title: Visual Treats created/ curated by Konrad Pitala
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffca09'
    - '#ffffff'
    - '#d61e54'
    - '#000000'
    - '#009ca2'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
